version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.7.1
    volumes:
      - /home/ubuntu/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.7.1
    volumes:
      - /home/ubuntu/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /home/ubuntu/nginx/log:/var/log/nginx
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
