version: '3.9'

networks:
  task25:

services:
  loki:
    image: grafana/loki:2.7.1
    volumes:
      - /home/ubuntu/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - task25

  promtail:
    image: grafana/promtail:2.7.1
    volumes:
      - /home/ubuntu/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /home/ubuntu/nginx/log:/var/log/nginx
      - /home/ubuntu/apache/log:/var/log/apache
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - task25

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    networks:
      - task25

  alertmanager:
    image: prom/alertmanager:v0.21.0
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'
    networks:
      - task25

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - task25

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /:/host:ro
    container_name: exporter
    command:
      - --path.rootfs=/host
    ports:
      - 9100:9100
    restart: unless-stopped
    networks:
      - task25
