{
 "title": "Task25-dashboard",
 "description": "Task25-dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 -(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx-logs",
   "type": "logs",
   "description": "Nginx-logs",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"nginxlogs\"} |= ``"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 - (avg by (name) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache-logs",
   "type": "logs",
   "description": "Apache-logs",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"apachelogs\"} |= ``"
    }
   ]
  }
 ]
}