version: "3.9"

services:
  nginx:
    image: mpgrail/task25:nginx
    volumes:
      - /home/ubuntu/nginx/log:/var/log/nginx
    ports:
      - "80:80"
    networks:
      - task25

  apache:
    image: mpgrail/task25:apache
    volumes:
      - /home/ubuntu/apache/log:/var/log/apache2
    ports:
      - "8080:8080"
    networks:
      - task25

networks:
  task25:
